In [26]:
import numpy as np
from numpy.linalg import pinv  # pseudo-inverse

np.set_printoptions(precision=2, sign=' ', suppress=True)

In [27]:
X = np.array([[1, 2104, 5, 1, 45],
              [1, 1416, 3, 2, 40],
              [1, 1534, 3, 2, 30],
              [1,  852, 2, 1, 36]])

In [28]:
X

array([[   1, 2104,    5,    1,   45],
       [   1, 1416,    3,    2,   40],
       [   1, 1534,    3,    2,   30],
       [   1,  852,    2,    1,   36]])

In [29]:
X.shape

(4, 5)

In [30]:
y = np.array([[460.],
              [232.],
              [315.],
              [178.]])

In [31]:
theta = pinv(X) @ y

In [32]:
theta

array([[188.4 ],
       [  0.39],
       [-56.14],
       [-92.97],
       [ -3.74]])

In [33]:
print(X @ theta)

[[ 460.]
 [ 232.]
 [ 315.]
 [ 178.]]


In [34]:
print(y)

[[ 460.]
 [ 232.]
 [ 315.]
 [ 178.]]


In [35]:
np.allclose(X @ theta, y)

True

In [36]:
theta = pinv(X.T @ X) @ X.T @ y

In [37]:
from numpy.linalg import inv, pinv

In [49]:
A = np.random.randn(3, 3)

In [50]:
A.shape

(3, 3)

In [53]:
A

array([[ 1.04,  0.8 , -0.72],
       [ 0.18, -1.54, -1.59],
       [ 0.13, -2.67,  0.94]])

In [52]:
inv(A)

array([[ 0.95, -0.19,  0.4 ],
       [ 0.06, -0.18, -0.25],
       [ 0.04, -0.48,  0.29]])

In [54]:
pinv(A)

array([[ 0.95, -0.19,  0.4 ],
       [ 0.06, -0.18, -0.25],
       [ 0.04, -0.48,  0.29]])

In [55]:
np.allclose(inv(A), pinv(A))

True

In [56]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [2, 4, 6]])

In [58]:
pinv(A)

array([[-0.19,  0.44, -0.38],
       [-0.02,  0.11, -0.04],
       [ 0.14, -0.22,  0.29]])

In [60]:
X = np.array([[1, 2104, 5, 1, 45],
              [1, 1416, 3, 2, 40],
              [1, 1534, 3, 2, 30],
              [1,  852, 2, 1, 36],
              [1, 3000, 4, 1, 38]])

In [61]:
y = np.array([[460.],
              [232.],
              [315.],
              [178.],
              [540.]])

In [62]:
theta = pinv(X.T @ X) @ X.T @ y

In [63]:
theta

array([[247.03],
       [  0.11],
       [ 68.55],
       [-49.32],
       [ -6.99]])

In [64]:
X @ theta

array([[ 460.],
       [ 232.],
       [ 315.],
       [ 178.],
       [ 540.]])

In [65]:
y

array([[ 460.],
       [ 232.],
       [ 315.],
       [ 178.],
       [ 540.]])